// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "volpe-framework/comms/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateImageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageName      string                 `protobuf:"bytes,1,opt,name=imageName,proto3" json:"imageName,omitempty"`
	ImageSizeBytes int32                  `protobuf:"varint,2,opt,name=imageSizeBytes,proto3" json:"imageSizeBytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateImageRequest) Reset() {
	*x = CreateImageRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageRequest) ProtoMessage() {}

func (x *CreateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageRequest.ProtoReflect.Descriptor instead.
func (*CreateImageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateImageRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *CreateImageRequest) GetImageSizeBytes() int32 {
	if x != nil {
		return x.ImageSizeBytes
	}
	return 0
}

type ImageChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageChunk) Reset() {
	*x = ImageChunk{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageChunk) ProtoMessage() {}

func (x *ImageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageChunk.ProtoReflect.Descriptor instead.
func (*ImageChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ImageChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Result) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RegisterProblemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*RegisterProblemRequest_Details
	//	*RegisterProblemRequest_Image
	Data          isRegisterProblemRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProblemRequest) Reset() {
	*x = RegisterProblemRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProblemRequest) ProtoMessage() {}

func (x *RegisterProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProblemRequest.ProtoReflect.Descriptor instead.
func (*RegisterProblemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterProblemRequest) GetData() isRegisterProblemRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RegisterProblemRequest) GetDetails() *ProblemDetails {
	if x != nil {
		if x, ok := x.Data.(*RegisterProblemRequest_Details); ok {
			return x.Details
		}
	}
	return nil
}

func (x *RegisterProblemRequest) GetImage() *ImageChunk {
	if x != nil {
		if x, ok := x.Data.(*RegisterProblemRequest_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isRegisterProblemRequest_Data interface {
	isRegisterProblemRequest_Data()
}

type RegisterProblemRequest_Details struct {
	Details *ProblemDetails `protobuf:"bytes,1,opt,name=details,proto3,oneof"`
}

type RegisterProblemRequest_Image struct {
	Image *ImageChunk `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*RegisterProblemRequest_Details) isRegisterProblemRequest_Data() {}

func (*RegisterProblemRequest_Image) isRegisterProblemRequest_Data() {}

type ProblemDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProblemID      string                 `protobuf:"bytes,1,opt,name=problemID,proto3" json:"problemID,omitempty"`
	ImageSizeBytes int32                  `protobuf:"varint,2,opt,name=imageSizeBytes,proto3" json:"imageSizeBytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProblemDetails) Reset() {
	*x = ProblemDetails{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemDetails) ProtoMessage() {}

func (x *ProblemDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemDetails.ProtoReflect.Descriptor instead.
func (*ProblemDetails) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *ProblemDetails) GetProblemID() string {
	if x != nil {
		return x.ProblemID
	}
	return ""
}

func (x *ProblemDetails) GetImageSizeBytes() int32 {
	if x != nil {
		return x.ImageSizeBytes
	}
	return 0
}

type StartProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     string                 `protobuf:"bytes,1,opt,name=problemID,proto3" json:"problemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProblemRequest) Reset() {
	*x = StartProblemRequest{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProblemRequest) ProtoMessage() {}

func (x *StartProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProblemRequest.ProtoReflect.Descriptor instead.
func (*StartProblemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *StartProblemRequest) GetProblemID() string {
	if x != nil {
		return x.ProblemID
	}
	return ""
}

type StreamResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     string                 `protobuf:"bytes,1,opt,name=problemID,proto3" json:"problemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResultsRequest) Reset() {
	*x = StreamResultsRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResultsRequest) ProtoMessage() {}

func (x *StreamResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResultsRequest.ProtoReflect.Descriptor instead.
func (*StreamResultsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *StreamResultsRequest) GetProblemID() string {
	if x != nil {
		return x.ProblemID
	}
	return ""
}

type ProblemResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     string                 `protobuf:"bytes,1,opt,name=problemID,proto3" json:"problemID,omitempty"`
	BestResults   *common.Population     `protobuf:"bytes,2,opt,name=bestResults,proto3" json:"bestResults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProblemResult) Reset() {
	*x = ProblemResult{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemResult) ProtoMessage() {}

func (x *ProblemResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemResult.ProtoReflect.Descriptor instead.
func (*ProblemResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *ProblemResult) GetProblemID() string {
	if x != nil {
		return x.ProblemID
	}
	return ""
}

func (x *ProblemResult) GetBestResults() *common.Population {
	if x != nil {
		return x.BestResults
	}
	return nil
}

type AbortProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     string                 `protobuf:"bytes,1,opt,name=problemID,proto3" json:"problemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortProblemRequest) Reset() {
	*x = AbortProblemRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortProblemRequest) ProtoMessage() {}

func (x *AbortProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortProblemRequest.ProtoReflect.Descriptor instead.
func (*AbortProblemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *AbortProblemRequest) GetProblemID() string {
	if x != nil {
		return x.ProblemID
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x1a\fcommon.proto\"Z\n" +
	"\x12CreateImageRequest\x12\x1c\n" +
	"\timageName\x18\x01 \x01(\tR\timageName\x12&\n" +
	"\x0eimageSizeBytes\x18\x02 \x01(\x05R\x0eimageSizeBytes\" \n" +
	"\n" +
	"ImageChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"F\n" +
	"\x06Result\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage\"r\n" +
	"\x16RegisterProblemRequest\x12+\n" +
	"\adetails\x18\x01 \x01(\v2\x0f.ProblemDetailsH\x00R\adetails\x12#\n" +
	"\x05image\x18\x02 \x01(\v2\v.ImageChunkH\x00R\x05imageB\x06\n" +
	"\x04data\"V\n" +
	"\x0eProblemDetails\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\tR\tproblemID\x12&\n" +
	"\x0eimageSizeBytes\x18\x02 \x01(\x05R\x0eimageSizeBytes\"3\n" +
	"\x13StartProblemRequest\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\tR\tproblemID\"4\n" +
	"\x14StreamResultsRequest\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\tR\tproblemID\"\\\n" +
	"\rProblemResult\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\tR\tproblemID\x12-\n" +
	"\vbestResults\x18\x02 \x01(\v2\v.PopulationR\vbestResults\"3\n" +
	"\x13AbortProblemRequest\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\tR\tproblemID2\xe1\x01\n" +
	"\bVolpeAPI\x127\n" +
	"\x0fRegisterProblem\x12\x17.RegisterProblemRequest\x1a\a.Result\"\x00(\x01\x12/\n" +
	"\fStartProblem\x12\x14.StartProblemRequest\x1a\a.Result\"\x00\x12:\n" +
	"\rStreamResults\x12\x15.StreamResultsRequest\x1a\x0e.ProblemResult\"\x000\x01\x12/\n" +
	"\fAbortProblem\x12\x14.AbortProblemRequest\x1a\a.Result\"\x00B\x1bZ\x19volpe-framework/comms/apib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_goTypes = []any{
	(*CreateImageRequest)(nil),     // 0: CreateImageRequest
	(*ImageChunk)(nil),             // 1: ImageChunk
	(*Result)(nil),                 // 2: Result
	(*RegisterProblemRequest)(nil), // 3: RegisterProblemRequest
	(*ProblemDetails)(nil),         // 4: ProblemDetails
	(*StartProblemRequest)(nil),    // 5: StartProblemRequest
	(*StreamResultsRequest)(nil),   // 6: StreamResultsRequest
	(*ProblemResult)(nil),          // 7: ProblemResult
	(*AbortProblemRequest)(nil),    // 8: AbortProblemRequest
	(*common.Population)(nil),      // 9: Population
}
var file_api_proto_depIdxs = []int32{
	4, // 0: RegisterProblemRequest.details:type_name -> ProblemDetails
	1, // 1: RegisterProblemRequest.image:type_name -> ImageChunk
	9, // 2: ProblemResult.bestResults:type_name -> Population
	3, // 3: VolpeAPI.RegisterProblem:input_type -> RegisterProblemRequest
	5, // 4: VolpeAPI.StartProblem:input_type -> StartProblemRequest
	6, // 5: VolpeAPI.StreamResults:input_type -> StreamResultsRequest
	8, // 6: VolpeAPI.AbortProblem:input_type -> AbortProblemRequest
	2, // 7: VolpeAPI.RegisterProblem:output_type -> Result
	2, // 8: VolpeAPI.StartProblem:output_type -> Result
	7, // 9: VolpeAPI.StreamResults:output_type -> ProblemResult
	2, // 10: VolpeAPI.AbortProblem:output_type -> Result
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[3].OneofWrappers = []any{
		(*RegisterProblemRequest_Details)(nil),
		(*RegisterProblemRequest_Image)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
