// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "volpe-framework/comms/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateImageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageName      string                 `protobuf:"bytes,1,opt,name=imageName,proto3" json:"imageName,omitempty"`
	ImageSizeBytes int32                  `protobuf:"varint,2,opt,name=imageSizeBytes,proto3" json:"imageSizeBytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateImageRequest) Reset() {
	*x = CreateImageRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageRequest) ProtoMessage() {}

func (x *CreateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageRequest.ProtoReflect.Descriptor instead.
func (*CreateImageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateImageRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *CreateImageRequest) GetImageSizeBytes() int32 {
	if x != nil {
		return x.ImageSizeBytes
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Result) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StartProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     string                 `protobuf:"bytes,1,opt,name=problemID,proto3" json:"problemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProblemRequest) Reset() {
	*x = StartProblemRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProblemRequest) ProtoMessage() {}

func (x *StartProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProblemRequest.ProtoReflect.Descriptor instead.
func (*StartProblemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *StartProblemRequest) GetProblemID() string {
	if x != nil {
		return x.ProblemID
	}
	return ""
}

type StreamResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     string                 `protobuf:"bytes,1,opt,name=problemID,proto3" json:"problemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResultsRequest) Reset() {
	*x = StreamResultsRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResultsRequest) ProtoMessage() {}

func (x *StreamResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResultsRequest.ProtoReflect.Descriptor instead.
func (*StreamResultsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *StreamResultsRequest) GetProblemID() string {
	if x != nil {
		return x.ProblemID
	}
	return ""
}

type ProblemResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     string                 `protobuf:"bytes,1,opt,name=problemID,proto3" json:"problemID,omitempty"`
	BestResults   *common.Population     `protobuf:"bytes,2,opt,name=bestResults,proto3" json:"bestResults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProblemResult) Reset() {
	*x = ProblemResult{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemResult) ProtoMessage() {}

func (x *ProblemResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemResult.ProtoReflect.Descriptor instead.
func (*ProblemResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *ProblemResult) GetProblemID() string {
	if x != nil {
		return x.ProblemID
	}
	return ""
}

func (x *ProblemResult) GetBestResults() *common.Population {
	if x != nil {
		return x.BestResults
	}
	return nil
}

type AbortProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     string                 `protobuf:"bytes,1,opt,name=problemID,proto3" json:"problemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortProblemRequest) Reset() {
	*x = AbortProblemRequest{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortProblemRequest) ProtoMessage() {}

func (x *AbortProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortProblemRequest.ProtoReflect.Descriptor instead.
func (*AbortProblemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *AbortProblemRequest) GetProblemID() string {
	if x != nil {
		return x.ProblemID
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x1a\fcommon.proto\"Z\n" +
	"\x12CreateImageRequest\x12\x1c\n" +
	"\timageName\x18\x01 \x01(\tR\timageName\x12&\n" +
	"\x0eimageSizeBytes\x18\x02 \x01(\x05R\x0eimageSizeBytes\"F\n" +
	"\x06Result\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage\"3\n" +
	"\x13StartProblemRequest\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\tR\tproblemID\"4\n" +
	"\x14StreamResultsRequest\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\tR\tproblemID\"\\\n" +
	"\rProblemResult\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\tR\tproblemID\x12-\n" +
	"\vbestResults\x18\x02 \x01(\v2\v.PopulationR\vbestResults\"3\n" +
	"\x13AbortProblemRequest\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\tR\tproblemID2\xdc\x01\n" +
	"\bVolpeAPI\x122\n" +
	"\x0fRegisterProblem\x12\x12.ImageStreamObject\x1a\a.Result\"\x00(\x01\x12/\n" +
	"\fStartProblem\x12\x14.StartProblemRequest\x1a\a.Result\"\x00\x12:\n" +
	"\rStreamResults\x12\x15.StreamResultsRequest\x1a\x0e.ProblemResult\"\x000\x01\x12/\n" +
	"\fAbortProblem\x12\x14.AbortProblemRequest\x1a\a.Result\"\x00B\x1bZ\x19volpe-framework/comms/apib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_goTypes = []any{
	(*CreateImageRequest)(nil),       // 0: CreateImageRequest
	(*Result)(nil),                   // 1: Result
	(*StartProblemRequest)(nil),      // 2: StartProblemRequest
	(*StreamResultsRequest)(nil),     // 3: StreamResultsRequest
	(*ProblemResult)(nil),            // 4: ProblemResult
	(*AbortProblemRequest)(nil),      // 5: AbortProblemRequest
	(*common.Population)(nil),        // 6: Population
	(*common.ImageStreamObject)(nil), // 7: ImageStreamObject
}
var file_api_proto_depIdxs = []int32{
	6, // 0: ProblemResult.bestResults:type_name -> Population
	7, // 1: VolpeAPI.RegisterProblem:input_type -> ImageStreamObject
	2, // 2: VolpeAPI.StartProblem:input_type -> StartProblemRequest
	3, // 3: VolpeAPI.StreamResults:input_type -> StreamResultsRequest
	5, // 4: VolpeAPI.AbortProblem:input_type -> AbortProblemRequest
	1, // 5: VolpeAPI.RegisterProblem:output_type -> Result
	1, // 6: VolpeAPI.StartProblem:output_type -> Result
	4, // 7: VolpeAPI.StreamResults:output_type -> ProblemResult
	1, // 8: VolpeAPI.AbortProblem:output_type -> Result
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
