// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VolpeAPI_RegisterProblem_FullMethodName = "/VolpeAPI/RegisterProblem"
	VolpeAPI_StartProblem_FullMethodName    = "/VolpeAPI/StartProblem"
	VolpeAPI_StreamResults_FullMethodName   = "/VolpeAPI/StreamResults"
	VolpeAPI_AbortProblem_FullMethodName    = "/VolpeAPI/AbortProblem"
)

// VolpeAPIClient is the client API for VolpeAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VolpeAPIClient interface {
	RegisterProblem(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RegisterProblemRequest, Result], error)
	StartProblem(ctx context.Context, in *StartProblemRequest, opts ...grpc.CallOption) (*Result, error)
	StreamResults(ctx context.Context, in *StreamResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProblemResult], error)
	AbortProblem(ctx context.Context, in *AbortProblemRequest, opts ...grpc.CallOption) (*Result, error)
}

type volpeAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewVolpeAPIClient(cc grpc.ClientConnInterface) VolpeAPIClient {
	return &volpeAPIClient{cc}
}

func (c *volpeAPIClient) RegisterProblem(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RegisterProblemRequest, Result], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VolpeAPI_ServiceDesc.Streams[0], VolpeAPI_RegisterProblem_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterProblemRequest, Result]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolpeAPI_RegisterProblemClient = grpc.ClientStreamingClient[RegisterProblemRequest, Result]

func (c *volpeAPIClient) StartProblem(ctx context.Context, in *StartProblemRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, VolpeAPI_StartProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volpeAPIClient) StreamResults(ctx context.Context, in *StreamResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProblemResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VolpeAPI_ServiceDesc.Streams[1], VolpeAPI_StreamResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamResultsRequest, ProblemResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolpeAPI_StreamResultsClient = grpc.ServerStreamingClient[ProblemResult]

func (c *volpeAPIClient) AbortProblem(ctx context.Context, in *AbortProblemRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, VolpeAPI_AbortProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolpeAPIServer is the server API for VolpeAPI service.
// All implementations must embed UnimplementedVolpeAPIServer
// for forward compatibility.
type VolpeAPIServer interface {
	RegisterProblem(grpc.ClientStreamingServer[RegisterProblemRequest, Result]) error
	StartProblem(context.Context, *StartProblemRequest) (*Result, error)
	StreamResults(*StreamResultsRequest, grpc.ServerStreamingServer[ProblemResult]) error
	AbortProblem(context.Context, *AbortProblemRequest) (*Result, error)
	mustEmbedUnimplementedVolpeAPIServer()
}

// UnimplementedVolpeAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolpeAPIServer struct{}

func (UnimplementedVolpeAPIServer) RegisterProblem(grpc.ClientStreamingServer[RegisterProblemRequest, Result]) error {
	return status.Errorf(codes.Unimplemented, "method RegisterProblem not implemented")
}
func (UnimplementedVolpeAPIServer) StartProblem(context.Context, *StartProblemRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProblem not implemented")
}
func (UnimplementedVolpeAPIServer) StreamResults(*StreamResultsRequest, grpc.ServerStreamingServer[ProblemResult]) error {
	return status.Errorf(codes.Unimplemented, "method StreamResults not implemented")
}
func (UnimplementedVolpeAPIServer) AbortProblem(context.Context, *AbortProblemRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortProblem not implemented")
}
func (UnimplementedVolpeAPIServer) mustEmbedUnimplementedVolpeAPIServer() {}
func (UnimplementedVolpeAPIServer) testEmbeddedByValue()                  {}

// UnsafeVolpeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolpeAPIServer will
// result in compilation errors.
type UnsafeVolpeAPIServer interface {
	mustEmbedUnimplementedVolpeAPIServer()
}

func RegisterVolpeAPIServer(s grpc.ServiceRegistrar, srv VolpeAPIServer) {
	// If the following call pancis, it indicates UnimplementedVolpeAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolpeAPI_ServiceDesc, srv)
}

func _VolpeAPI_RegisterProblem_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VolpeAPIServer).RegisterProblem(&grpc.GenericServerStream[RegisterProblemRequest, Result]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolpeAPI_RegisterProblemServer = grpc.ClientStreamingServer[RegisterProblemRequest, Result]

func _VolpeAPI_StartProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolpeAPIServer).StartProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolpeAPI_StartProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolpeAPIServer).StartProblem(ctx, req.(*StartProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolpeAPI_StreamResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamResultsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VolpeAPIServer).StreamResults(m, &grpc.GenericServerStream[StreamResultsRequest, ProblemResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolpeAPI_StreamResultsServer = grpc.ServerStreamingServer[ProblemResult]

func _VolpeAPI_AbortProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolpeAPIServer).AbortProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolpeAPI_AbortProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolpeAPIServer).AbortProblem(ctx, req.(*AbortProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VolpeAPI_ServiceDesc is the grpc.ServiceDesc for VolpeAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolpeAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VolpeAPI",
	HandlerType: (*VolpeAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartProblem",
			Handler:    _VolpeAPI_StartProblem_Handler,
		},
		{
			MethodName: "AbortProblem",
			Handler:    _VolpeAPI_AbortProblem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterProblem",
			Handler:       _VolpeAPI_RegisterProblem_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamResults",
			Handler:       _VolpeAPI_StreamResults_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
