// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: volpe.proto

package volpe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "volpe-framework/comms/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerID) Reset() {
	*x = WorkerID{}
	mi := &file_volpe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerID) ProtoMessage() {}

func (x *WorkerID) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerID.ProtoReflect.Descriptor instead.
func (*WorkerID) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MasterMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*MasterMessage_AdjInst
	//	*MasterMessage_Migration
	Message       isMasterMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterMessage) Reset() {
	*x = MasterMessage{}
	mi := &file_volpe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterMessage) ProtoMessage() {}

func (x *MasterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterMessage.ProtoReflect.Descriptor instead.
func (*MasterMessage) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{1}
}

func (x *MasterMessage) GetMessage() isMasterMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MasterMessage) GetAdjInst() *AdjustInstancesMessage {
	if x != nil {
		if x, ok := x.Message.(*MasterMessage_AdjInst); ok {
			return x.AdjInst
		}
	}
	return nil
}

func (x *MasterMessage) GetMigration() *MigrationMessage {
	if x != nil {
		if x, ok := x.Message.(*MasterMessage_Migration); ok {
			return x.Migration
		}
	}
	return nil
}

type isMasterMessage_Message interface {
	isMasterMessage_Message()
}

type MasterMessage_AdjInst struct {
	AdjInst *AdjustInstancesMessage `protobuf:"bytes,2,opt,name=adjInst,proto3,oneof"`
}

type MasterMessage_Migration struct {
	Migration *MigrationMessage `protobuf:"bytes,4,opt,name=migration,proto3,oneof"`
}

func (*MasterMessage_AdjInst) isMasterMessage_Message() {}

func (*MasterMessage_Migration) isMasterMessage_Message() {}

type AdjustInstancesMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     string                 `protobuf:"bytes,1,opt,name=problemID,proto3" json:"problemID,omitempty"`
	Instances     int32                  `protobuf:"varint,3,opt,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustInstancesMessage) Reset() {
	*x = AdjustInstancesMessage{}
	mi := &file_volpe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustInstancesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustInstancesMessage) ProtoMessage() {}

func (x *AdjustInstancesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustInstancesMessage.ProtoReflect.Descriptor instead.
func (*AdjustInstancesMessage) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{2}
}

func (x *AdjustInstancesMessage) GetProblemID() string {
	if x != nil {
		return x.ProblemID
	}
	return ""
}

func (x *AdjustInstancesMessage) GetInstances() int32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

type WorkerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerID      *WorkerID              `protobuf:"bytes,1,opt,name=workerID,proto3" json:"workerID,omitempty"`
	CpuCount      int32                  `protobuf:"varint,2,opt,name=cpuCount,proto3" json:"cpuCount,omitempty"`
	MemoryGB      float32                `protobuf:"fixed32,3,opt,name=memoryGB,proto3" json:"memoryGB,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHello) Reset() {
	*x = WorkerHello{}
	mi := &file_volpe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHello) ProtoMessage() {}

func (x *WorkerHello) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHello.ProtoReflect.Descriptor instead.
func (*WorkerHello) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerHello) GetWorkerID() *WorkerID {
	if x != nil {
		return x.WorkerID
	}
	return nil
}

func (x *WorkerHello) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *WorkerHello) GetMemoryGB() float32 {
	if x != nil {
		return x.MemoryGB
	}
	return 0
}

type MigrationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerID      string                 `protobuf:"bytes,1,opt,name=workerID,proto3" json:"workerID,omitempty"`
	ContainerID   int32                  `protobuf:"varint,2,opt,name=containerID,proto3" json:"containerID,omitempty"`
	Population    *common.Population     `protobuf:"bytes,3,opt,name=population,proto3" json:"population,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationMessage) Reset() {
	*x = MigrationMessage{}
	mi := &file_volpe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationMessage) ProtoMessage() {}

func (x *MigrationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationMessage.ProtoReflect.Descriptor instead.
func (*MigrationMessage) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{4}
}

func (x *MigrationMessage) GetWorkerID() string {
	if x != nil {
		return x.WorkerID
	}
	return ""
}

func (x *MigrationMessage) GetContainerID() int32 {
	if x != nil {
		return x.ContainerID
	}
	return 0
}

func (x *MigrationMessage) GetPopulation() *common.Population {
	if x != nil {
		return x.Population
	}
	return nil
}

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// can be metrics, or subpopulation
	//
	// Types that are valid to be assigned to Message:
	//
	//	*WorkerMessage_Metrics
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Migration
	Message       isWorkerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_volpe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{5}
}

func (x *WorkerMessage) GetMessage() isWorkerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WorkerMessage) GetMetrics() *DeviceMetricsMessage {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *WorkerMessage) GetHello() *WorkerHello {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetMigration() *MigrationMessage {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Migration); ok {
			return x.Migration
		}
	}
	return nil
}

type isWorkerMessage_Message interface {
	isWorkerMessage_Message()
}

type WorkerMessage_Metrics struct {
	Metrics *DeviceMetricsMessage `protobuf:"bytes,1,opt,name=metrics,proto3,oneof"`
}

type WorkerMessage_Hello struct {
	Hello *WorkerHello `protobuf:"bytes,3,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Migration struct {
	Migration *MigrationMessage `protobuf:"bytes,4,opt,name=migration,proto3,oneof"`
}

func (*WorkerMessage_Metrics) isWorkerMessage_Message() {}

func (*WorkerMessage_Hello) isWorkerMessage_Message() {}

func (*WorkerMessage_Migration) isWorkerMessage_Message() {}

type DeviceMetricsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerID      string                 `protobuf:"bytes,1,opt,name=workerID,proto3" json:"workerID,omitempty"`
	CpuUtilPerc   float32                `protobuf:"fixed32,2,opt,name=cpuUtilPerc,proto3" json:"cpuUtilPerc,omitempty"`
	MemUsageGB    float32                `protobuf:"fixed32,3,opt,name=memUsageGB,proto3" json:"memUsageGB,omitempty"`
	NetTxBytes    uint32                 `protobuf:"varint,4,opt,name=netTxBytes,proto3" json:"netTxBytes,omitempty"`
	NetRxBytes    uint32                 `protobuf:"varint,5,opt,name=netRxBytes,proto3" json:"netRxBytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceMetricsMessage) Reset() {
	*x = DeviceMetricsMessage{}
	mi := &file_volpe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceMetricsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMetricsMessage) ProtoMessage() {}

func (x *DeviceMetricsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceMetricsMessage.ProtoReflect.Descriptor instead.
func (*DeviceMetricsMessage) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceMetricsMessage) GetWorkerID() string {
	if x != nil {
		return x.WorkerID
	}
	return ""
}

func (x *DeviceMetricsMessage) GetCpuUtilPerc() float32 {
	if x != nil {
		return x.CpuUtilPerc
	}
	return 0
}

func (x *DeviceMetricsMessage) GetMemUsageGB() float32 {
	if x != nil {
		return x.MemUsageGB
	}
	return 0
}

func (x *DeviceMetricsMessage) GetNetTxBytes() uint32 {
	if x != nil {
		return x.NetTxBytes
	}
	return 0
}

func (x *DeviceMetricsMessage) GetNetRxBytes() uint32 {
	if x != nil {
		return x.NetRxBytes
	}
	return 0
}

type ApplicationMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUtil       float32                `protobuf:"fixed32,1,opt,name=cpuUtil,proto3" json:"cpuUtil,omitempty"`
	MemUsage      float32                `protobuf:"fixed32,2,opt,name=memUsage,proto3" json:"memUsage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationMetrics) Reset() {
	*x = ApplicationMetrics{}
	mi := &file_volpe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationMetrics) ProtoMessage() {}

func (x *ApplicationMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationMetrics.ProtoReflect.Descriptor instead.
func (*ApplicationMetrics) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{7}
}

func (x *ApplicationMetrics) GetCpuUtil() float32 {
	if x != nil {
		return x.CpuUtil
	}
	return 0
}

func (x *ApplicationMetrics) GetMemUsage() float32 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

type ProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     string                 `protobuf:"bytes,1,opt,name=problemID,proto3" json:"problemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProblemRequest) Reset() {
	*x = ProblemRequest{}
	mi := &file_volpe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemRequest) ProtoMessage() {}

func (x *ProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemRequest.ProtoReflect.Descriptor instead.
func (*ProblemRequest) Descriptor() ([]byte, []int) {
	return file_volpe_proto_rawDescGZIP(), []int{8}
}

func (x *ProblemRequest) GetProblemID() string {
	if x != nil {
		return x.ProblemID
	}
	return ""
}

var File_volpe_proto protoreflect.FileDescriptor

const file_volpe_proto_rawDesc = "" +
	"\n" +
	"\vvolpe.proto\x1a\fcommon.proto\"\x1a\n" +
	"\bWorkerID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x82\x01\n" +
	"\rMasterMessage\x123\n" +
	"\aadjInst\x18\x02 \x01(\v2\x17.AdjustInstancesMessageH\x00R\aadjInst\x121\n" +
	"\tmigration\x18\x04 \x01(\v2\x11.MigrationMessageH\x00R\tmigrationB\t\n" +
	"\amessage\"T\n" +
	"\x16AdjustInstancesMessage\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\tR\tproblemID\x12\x1c\n" +
	"\tinstances\x18\x03 \x01(\x05R\tinstances\"l\n" +
	"\vWorkerHello\x12%\n" +
	"\bworkerID\x18\x01 \x01(\v2\t.WorkerIDR\bworkerID\x12\x1a\n" +
	"\bcpuCount\x18\x02 \x01(\x05R\bcpuCount\x12\x1a\n" +
	"\bmemoryGB\x18\x03 \x01(\x02R\bmemoryGB\"}\n" +
	"\x10MigrationMessage\x12\x1a\n" +
	"\bworkerID\x18\x01 \x01(\tR\bworkerID\x12 \n" +
	"\vcontainerID\x18\x02 \x01(\x05R\vcontainerID\x12+\n" +
	"\n" +
	"population\x18\x03 \x01(\v2\v.PopulationR\n" +
	"population\"\xa6\x01\n" +
	"\rWorkerMessage\x121\n" +
	"\ametrics\x18\x01 \x01(\v2\x15.DeviceMetricsMessageH\x00R\ametrics\x12$\n" +
	"\x05hello\x18\x03 \x01(\v2\f.WorkerHelloH\x00R\x05hello\x121\n" +
	"\tmigration\x18\x04 \x01(\v2\x11.MigrationMessageH\x00R\tmigrationB\t\n" +
	"\amessage\"\xb4\x01\n" +
	"\x14DeviceMetricsMessage\x12\x1a\n" +
	"\bworkerID\x18\x01 \x01(\tR\bworkerID\x12 \n" +
	"\vcpuUtilPerc\x18\x02 \x01(\x02R\vcpuUtilPerc\x12\x1e\n" +
	"\n" +
	"memUsageGB\x18\x03 \x01(\x02R\n" +
	"memUsageGB\x12\x1e\n" +
	"\n" +
	"netTxBytes\x18\x04 \x01(\rR\n" +
	"netTxBytes\x12\x1e\n" +
	"\n" +
	"netRxBytes\x18\x05 \x01(\rR\n" +
	"netRxBytes\"J\n" +
	"\x12ApplicationMetrics\x12\x18\n" +
	"\acpuUtil\x18\x01 \x01(\x02R\acpuUtil\x12\x1a\n" +
	"\bmemUsage\x18\x02 \x01(\x02R\bmemUsage\".\n" +
	"\x0eProblemRequest\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\tR\tproblemID2~\n" +
	"\vVolpeMaster\x124\n" +
	"\fStartStreams\x12\x0e.WorkerMessage\x1a\x0e.MasterMessage\"\x00(\x010\x01\x129\n" +
	"\x0eGetProblemData\x12\x0f.ProblemRequest\x1a\x12.ImageStreamObject\"\x000\x01B\x0fZ\r./comms/volpeb\x06proto3"

var (
	file_volpe_proto_rawDescOnce sync.Once
	file_volpe_proto_rawDescData []byte
)

func file_volpe_proto_rawDescGZIP() []byte {
	file_volpe_proto_rawDescOnce.Do(func() {
		file_volpe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_volpe_proto_rawDesc), len(file_volpe_proto_rawDesc)))
	})
	return file_volpe_proto_rawDescData
}

var file_volpe_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_volpe_proto_goTypes = []any{
	(*WorkerID)(nil),                 // 0: WorkerID
	(*MasterMessage)(nil),            // 1: MasterMessage
	(*AdjustInstancesMessage)(nil),   // 2: AdjustInstancesMessage
	(*WorkerHello)(nil),              // 3: WorkerHello
	(*MigrationMessage)(nil),         // 4: MigrationMessage
	(*WorkerMessage)(nil),            // 5: WorkerMessage
	(*DeviceMetricsMessage)(nil),     // 6: DeviceMetricsMessage
	(*ApplicationMetrics)(nil),       // 7: ApplicationMetrics
	(*ProblemRequest)(nil),           // 8: ProblemRequest
	(*common.Population)(nil),        // 9: Population
	(*common.ImageStreamObject)(nil), // 10: ImageStreamObject
}
var file_volpe_proto_depIdxs = []int32{
	2,  // 0: MasterMessage.adjInst:type_name -> AdjustInstancesMessage
	4,  // 1: MasterMessage.migration:type_name -> MigrationMessage
	0,  // 2: WorkerHello.workerID:type_name -> WorkerID
	9,  // 3: MigrationMessage.population:type_name -> Population
	6,  // 4: WorkerMessage.metrics:type_name -> DeviceMetricsMessage
	3,  // 5: WorkerMessage.hello:type_name -> WorkerHello
	4,  // 6: WorkerMessage.migration:type_name -> MigrationMessage
	5,  // 7: VolpeMaster.StartStreams:input_type -> WorkerMessage
	8,  // 8: VolpeMaster.GetProblemData:input_type -> ProblemRequest
	1,  // 9: VolpeMaster.StartStreams:output_type -> MasterMessage
	10, // 10: VolpeMaster.GetProblemData:output_type -> ImageStreamObject
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_volpe_proto_init() }
func file_volpe_proto_init() {
	if File_volpe_proto != nil {
		return
	}
	file_volpe_proto_msgTypes[1].OneofWrappers = []any{
		(*MasterMessage_AdjInst)(nil),
		(*MasterMessage_Migration)(nil),
	}
	file_volpe_proto_msgTypes[5].OneofWrappers = []any{
		(*WorkerMessage_Metrics)(nil),
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Migration)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_volpe_proto_rawDesc), len(file_volpe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_volpe_proto_goTypes,
		DependencyIndexes: file_volpe_proto_depIdxs,
		MessageInfos:      file_volpe_proto_msgTypes,
	}.Build()
	File_volpe_proto = out.File
	file_volpe_proto_goTypes = nil
	file_volpe_proto_depIdxs = nil
}
