// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: volpe.proto

package volpe

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "volpe-framework/comms/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VolpeMaster_StartStreams_FullMethodName   = "/VolpeMaster/StartStreams"
	VolpeMaster_GetProblemData_FullMethodName = "/VolpeMaster/GetProblemData"
)

// VolpeMasterClient is the client API for VolpeMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VolpeMasterClient interface {
	StartStreams(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, MasterMessage], error)
	GetProblemData(ctx context.Context, in *ProblemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.ImageStreamObject], error)
}

type volpeMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewVolpeMasterClient(cc grpc.ClientConnInterface) VolpeMasterClient {
	return &volpeMasterClient{cc}
}

func (c *volpeMasterClient) StartStreams(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, MasterMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VolpeMaster_ServiceDesc.Streams[0], VolpeMaster_StartStreams_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, MasterMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolpeMaster_StartStreamsClient = grpc.BidiStreamingClient[WorkerMessage, MasterMessage]

func (c *volpeMasterClient) GetProblemData(ctx context.Context, in *ProblemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[common.ImageStreamObject], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VolpeMaster_ServiceDesc.Streams[1], VolpeMaster_GetProblemData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProblemRequest, common.ImageStreamObject]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolpeMaster_GetProblemDataClient = grpc.ServerStreamingClient[common.ImageStreamObject]

// VolpeMasterServer is the server API for VolpeMaster service.
// All implementations must embed UnimplementedVolpeMasterServer
// for forward compatibility.
type VolpeMasterServer interface {
	StartStreams(grpc.BidiStreamingServer[WorkerMessage, MasterMessage]) error
	GetProblemData(*ProblemRequest, grpc.ServerStreamingServer[common.ImageStreamObject]) error
	mustEmbedUnimplementedVolpeMasterServer()
}

// UnimplementedVolpeMasterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolpeMasterServer struct{}

func (UnimplementedVolpeMasterServer) StartStreams(grpc.BidiStreamingServer[WorkerMessage, MasterMessage]) error {
	return status.Error(codes.Unimplemented, "method StartStreams not implemented")
}
func (UnimplementedVolpeMasterServer) GetProblemData(*ProblemRequest, grpc.ServerStreamingServer[common.ImageStreamObject]) error {
	return status.Error(codes.Unimplemented, "method GetProblemData not implemented")
}
func (UnimplementedVolpeMasterServer) mustEmbedUnimplementedVolpeMasterServer() {}
func (UnimplementedVolpeMasterServer) testEmbeddedByValue()                     {}

// UnsafeVolpeMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolpeMasterServer will
// result in compilation errors.
type UnsafeVolpeMasterServer interface {
	mustEmbedUnimplementedVolpeMasterServer()
}

func RegisterVolpeMasterServer(s grpc.ServiceRegistrar, srv VolpeMasterServer) {
	// If the following call panics, it indicates UnimplementedVolpeMasterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolpeMaster_ServiceDesc, srv)
}

func _VolpeMaster_StartStreams_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VolpeMasterServer).StartStreams(&grpc.GenericServerStream[WorkerMessage, MasterMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolpeMaster_StartStreamsServer = grpc.BidiStreamingServer[WorkerMessage, MasterMessage]

func _VolpeMaster_GetProblemData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProblemRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VolpeMasterServer).GetProblemData(m, &grpc.GenericServerStream[ProblemRequest, common.ImageStreamObject]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolpeMaster_GetProblemDataServer = grpc.ServerStreamingServer[common.ImageStreamObject]

// VolpeMaster_ServiceDesc is the grpc.ServiceDesc for VolpeMaster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolpeMaster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VolpeMaster",
	HandlerType: (*VolpeMasterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartStreams",
			Handler:       _VolpeMaster_StartStreams_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetProblemData",
			Handler:       _VolpeMaster_GetProblemData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "volpe.proto",
}
