// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: volpe_container.proto

package container

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "volpe-framework/comms/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultIndividual struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Representation string                 `protobuf:"bytes,1,opt,name=representation,proto3" json:"representation,omitempty"`
	Fitness        float32                `protobuf:"fixed32,2,opt,name=fitness,proto3" json:"fitness,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResultIndividual) Reset() {
	*x = ResultIndividual{}
	mi := &file_volpe_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultIndividual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultIndividual) ProtoMessage() {}

func (x *ResultIndividual) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultIndividual.ProtoReflect.Descriptor instead.
func (*ResultIndividual) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{0}
}

func (x *ResultIndividual) GetRepresentation() string {
	if x != nil {
		return x.Representation
	}
	return ""
}

func (x *ResultIndividual) GetFitness() float32 {
	if x != nil {
		return x.Fitness
	}
	return 0
}

type ResultPopulation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ResultIndividual    `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultPopulation) Reset() {
	*x = ResultPopulation{}
	mi := &file_volpe_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultPopulation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultPopulation) ProtoMessage() {}

func (x *ResultPopulation) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultPopulation.ProtoReflect.Descriptor instead.
func (*ResultPopulation) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{1}
}

func (x *ResultPopulation) GetMembers() []*ResultIndividual {
	if x != nil {
		return x.Members
	}
	return nil
}

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_volpe_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{2}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Seed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          int32                  `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seed) Reset() {
	*x = Seed{}
	mi := &file_volpe_container_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seed) ProtoMessage() {}

func (x *Seed) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seed.ProtoReflect.Descriptor instead.
func (*Seed) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{3}
}

func (x *Seed) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type PopulationSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopulationSize) Reset() {
	*x = PopulationSize{}
	mi := &file_volpe_container_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopulationSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulationSize) ProtoMessage() {}

func (x *PopulationSize) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulationSize.ProtoReflect.Descriptor instead.
func (*PopulationSize) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{4}
}

func (x *PopulationSize) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_volpe_container_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{5}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_volpe_container_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_volpe_container_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_volpe_container_proto_rawDescGZIP(), []int{6}
}

func (x *Reply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_volpe_container_proto protoreflect.FileDescriptor

const file_volpe_container_proto_rawDesc = "" +
	"\n" +
	"\x15volpe_container.proto\x1a\fcommon.proto\"T\n" +
	"\x10ResultIndividual\x12&\n" +
	"\x0erepresentation\x18\x01 \x01(\tR\x0erepresentation\x12\x18\n" +
	"\afitness\x18\x02 \x01(\x02R\afitness\"?\n" +
	"\x10ResultPopulation\x12+\n" +
	"\amembers\x18\x01 \x03(\v2\x11.ResultIndividualR\amembers\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1a\n" +
	"\x04Seed\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\x05R\x04seed\"$\n" +
	"\x0ePopulationSize\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\";\n" +
	"\x05Reply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd8\x02\n" +
	"\x0eVolpeContainer\x12(\n" +
	"\bSayHello\x12\r.HelloRequest\x1a\v.HelloReply\"\x00\x12\x1f\n" +
	"\fInitFromSeed\x12\x05.Seed\x1a\x06.Reply\"\x00\x12/\n" +
	"\x16InitFromSeedPopulation\x12\v.Population\x1a\x06.Reply\"\x00\x123\n" +
	"\x11GetBestPopulation\x12\x0f.PopulationSize\x1a\v.Population\"\x00\x122\n" +
	"\n" +
	"GetResults\x12\x0f.PopulationSize\x1a\x11.ResultPopulation\"\x00\x121\n" +
	"\x14AdjustPopulationSize\x12\x0f.PopulationSize\x1a\x06.Reply\"\x00\x12.\n" +
	"\x11RunForGenerations\x12\x0f.PopulationSize\x1a\x06.Reply\"\x00B\x13Z\x11./comms/containerb\x06proto3"

var (
	file_volpe_container_proto_rawDescOnce sync.Once
	file_volpe_container_proto_rawDescData []byte
)

func file_volpe_container_proto_rawDescGZIP() []byte {
	file_volpe_container_proto_rawDescOnce.Do(func() {
		file_volpe_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_volpe_container_proto_rawDesc), len(file_volpe_container_proto_rawDesc)))
	})
	return file_volpe_container_proto_rawDescData
}

var file_volpe_container_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_volpe_container_proto_goTypes = []any{
	(*ResultIndividual)(nil),  // 0: ResultIndividual
	(*ResultPopulation)(nil),  // 1: ResultPopulation
	(*HelloRequest)(nil),      // 2: HelloRequest
	(*Seed)(nil),              // 3: Seed
	(*PopulationSize)(nil),    // 4: PopulationSize
	(*HelloReply)(nil),        // 5: HelloReply
	(*Reply)(nil),             // 6: Reply
	(*common.Population)(nil), // 7: Population
}
var file_volpe_container_proto_depIdxs = []int32{
	0, // 0: ResultPopulation.members:type_name -> ResultIndividual
	2, // 1: VolpeContainer.SayHello:input_type -> HelloRequest
	3, // 2: VolpeContainer.InitFromSeed:input_type -> Seed
	7, // 3: VolpeContainer.InitFromSeedPopulation:input_type -> Population
	4, // 4: VolpeContainer.GetBestPopulation:input_type -> PopulationSize
	4, // 5: VolpeContainer.GetResults:input_type -> PopulationSize
	4, // 6: VolpeContainer.AdjustPopulationSize:input_type -> PopulationSize
	4, // 7: VolpeContainer.RunForGenerations:input_type -> PopulationSize
	5, // 8: VolpeContainer.SayHello:output_type -> HelloReply
	6, // 9: VolpeContainer.InitFromSeed:output_type -> Reply
	6, // 10: VolpeContainer.InitFromSeedPopulation:output_type -> Reply
	7, // 11: VolpeContainer.GetBestPopulation:output_type -> Population
	1, // 12: VolpeContainer.GetResults:output_type -> ResultPopulation
	6, // 13: VolpeContainer.AdjustPopulationSize:output_type -> Reply
	6, // 14: VolpeContainer.RunForGenerations:output_type -> Reply
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_volpe_container_proto_init() }
func file_volpe_container_proto_init() {
	if File_volpe_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_volpe_container_proto_rawDesc), len(file_volpe_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_volpe_container_proto_goTypes,
		DependencyIndexes: file_volpe_container_proto_depIdxs,
		MessageInfos:      file_volpe_container_proto_msgTypes,
	}.Build()
	File_volpe_container_proto = out.File
	file_volpe_container_proto_goTypes = nil
	file_volpe_container_proto_depIdxs = nil
}
